# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-3995-ffdc95eddc45/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xck26-sfvc784-2LV-c
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/f0b6/hdl/verilog
    /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/c783/hdl/verilog
  } {
      /home/user/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/user/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/user/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/3718/hdl/sc_switchboard_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_2/synth/bd_2d9b_arsw_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_3/synth/bd_2d9b_rsw_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_4/synth/bd_2d9b_awsw_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_5/synth/bd_2d9b_wsw_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_6/synth/bd_2d9b_bsw_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/98d8/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_7/synth/bd_2d9b_s00mmu_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/2da8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_8/synth/bd_2d9b_s00tr_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/a950/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_9/synth/bd_2d9b_s00sic_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/cef3/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_10/synth/bd_2d9b_s00a2s_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/c783/hdl/sc_node_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_11/synth/bd_2d9b_sarn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_12/synth/bd_2d9b_srn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_13/synth/bd_2d9b_s01mmu_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_14/synth/bd_2d9b_s01tr_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_15/synth/bd_2d9b_s01sic_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_16/synth/bd_2d9b_s01a2s_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_17/synth/bd_2d9b_sawn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_18/synth/bd_2d9b_swn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_19/synth/bd_2d9b_sbn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_20/synth/bd_2d9b_s02mmu_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_21/synth/bd_2d9b_s02tr_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_22/synth/bd_2d9b_s02sic_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_23/synth/bd_2d9b_s02a2s_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_24/synth/bd_2d9b_sarn_1.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_25/synth/bd_2d9b_srn_1.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_26/synth/bd_2d9b_sawn_1.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_27/synth/bd_2d9b_swn_1.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_28/synth/bd_2d9b_sbn_1.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_29/synth/bd_2d9b_s03mmu_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_30/synth/bd_2d9b_s03tr_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_31/synth/bd_2d9b_s03sic_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_32/synth/bd_2d9b_s03a2s_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_33/synth/bd_2d9b_sarn_2.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_34/synth/bd_2d9b_srn_2.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_35/synth/bd_2d9b_s04mmu_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_36/synth/bd_2d9b_s04tr_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_37/synth/bd_2d9b_s04sic_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_38/synth/bd_2d9b_s04a2s_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_39/synth/bd_2d9b_sawn_2.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_40/synth/bd_2d9b_swn_2.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_41/synth/bd_2d9b_sbn_2.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_42/synth/bd_2d9b_s05mmu_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_43/synth/bd_2d9b_s05tr_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_44/synth/bd_2d9b_s05sic_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_45/synth/bd_2d9b_s05a2s_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_46/synth/bd_2d9b_sarn_3.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_47/synth/bd_2d9b_srn_3.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_48/synth/bd_2d9b_sawn_3.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_49/synth/bd_2d9b_swn_3.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_50/synth/bd_2d9b_sbn_3.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/7f4f/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_51/synth/bd_2d9b_m00s2a_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_52/synth/bd_2d9b_m00arn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_53/synth/bd_2d9b_m00rn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_54/synth/bd_2d9b_m00awn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_55/synth/bd_2d9b_m00wn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_56/synth/bd_2d9b_m00bn_0.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/1f04/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_57/synth/bd_2d9b_m00e_0.sv
    }
      rt::read_verilog -include {
    /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/f0b6/hdl/verilog
    /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/c783/hdl/verilog
  } {
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/e2d2/hdl/xlconstant_v1_1_vl_rfs.v
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_0/synth/bd_2d9b_one_0.v
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/synth/bd_2d9b.v
      /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/synth/kria_bd_smartconnect_0_0.v
    }
      rt::read_vhdl -lib xpm /home/user/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_3 /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/2a4f/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_15 /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/3a26/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_1/synth/bd_2d9b_psr_aclk_0.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-3995-ffdc95eddc45/realtime/kria_bd_smartconnect_0_0_synth.xdc
    rt::sdcChecksum
    set rt::top kria_bd_smartconnect_0_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-3995-ffdc95eddc45/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
