# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/kria_bd_smartconnect_0_1.xci
# IP: The module: 'kria_bd_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/bd_ed5a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_ed5a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_2/bd_ed5a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_3/bd_ed5a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_4/bd_ed5a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_ed5a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_ed5a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_7/bd_ed5a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_8/bd_ed5a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_9/bd_ed5a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_ed5a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_ed5a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_12/bd_ed5a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_13/bd_ed5a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_14/bd_ed5a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_15/bd_ed5a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_16/bd_ed5a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_17/bd_ed5a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_18/bd_ed5a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_19/bd_ed5a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_20/bd_ed5a_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_21/bd_ed5a_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_22/bd_ed5a_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_23/bd_ed5a_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_24/bd_ed5a_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_25/bd_ed5a_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_26/bd_ed5a_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_27/bd_ed5a_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_28/bd_ed5a_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_29/bd_ed5a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_30/bd_ed5a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_31/bd_ed5a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_32/bd_ed5a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_33/bd_ed5a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_34/bd_ed5a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_35/bd_ed5a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_ed5a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_2/bd_ed5a_arsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_3/bd_ed5a_rsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_4/bd_ed5a_awsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_ed5a_wsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_ed5a_bsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_ed5a_s00a2s_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_ed5a_sarn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_12/bd_ed5a_srn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_16/bd_ed5a_s01a2s_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_17/bd_ed5a_sawn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_18/bd_ed5a_swn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_19/bd_ed5a_sbn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_23/bd_ed5a_s02a2s_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_24/bd_ed5a_sarn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_25/bd_ed5a_srn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_26/bd_ed5a_sawn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_27/bd_ed5a_swn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_28/bd_ed5a_sbn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_29/bd_ed5a_m00s2a_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_30/bd_ed5a_m00arn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_31/bd_ed5a_m00rn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_32/bd_ed5a_m00awn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_33/bd_ed5a_m00wn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_34/bd_ed5a_m00bn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/kria_bd_smartconnect_0_1.xci
# IP: The module: 'kria_bd_smartconnect_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/bd_ed5a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_ed5a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_2/bd_ed5a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_3/bd_ed5a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_4/bd_ed5a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_ed5a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_ed5a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_7/bd_ed5a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_8/bd_ed5a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_9/bd_ed5a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_ed5a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_ed5a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_12/bd_ed5a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_13/bd_ed5a_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_14/bd_ed5a_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_15/bd_ed5a_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_16/bd_ed5a_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_17/bd_ed5a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_18/bd_ed5a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_19/bd_ed5a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_20/bd_ed5a_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_21/bd_ed5a_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_22/bd_ed5a_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_23/bd_ed5a_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_24/bd_ed5a_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_25/bd_ed5a_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_26/bd_ed5a_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_27/bd_ed5a_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_28/bd_ed5a_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_29/bd_ed5a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_30/bd_ed5a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_31/bd_ed5a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_32/bd_ed5a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_33/bd_ed5a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_34/bd_ed5a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_35/bd_ed5a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_1/bd_ed5a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_2/bd_ed5a_arsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_3/bd_ed5a_rsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_4/bd_ed5a_awsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_5/bd_ed5a_wsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_6/bd_ed5a_bsw_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_10/bd_ed5a_s00a2s_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_11/bd_ed5a_sarn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_12/bd_ed5a_srn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_16/bd_ed5a_s01a2s_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_17/bd_ed5a_sawn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_18/bd_ed5a_swn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_19/bd_ed5a_sbn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_23/bd_ed5a_s02a2s_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_24/bd_ed5a_sarn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_25/bd_ed5a_srn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_26/bd_ed5a_sawn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_27/bd_ed5a_swn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_28/bd_ed5a_sbn_1_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_29/bd_ed5a_m00s2a_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_30/bd_ed5a_m00arn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_31/bd_ed5a_m00rn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_32/bd_ed5a_m00awn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_33/bd_ed5a_m00wn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_34/bd_ed5a_m00bn_0_ooc.xdc

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
