# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/workspace/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/kria_bd_smartconnect_1_0.xci
# IP: The module: 'kria_bd_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/bd_edca.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_0/bd_edca_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_1/bd_edca_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_2/bd_edca_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_3/bd_edca_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_4/bd_edca_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_5/bd_edca_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_6/bd_edca_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_7/bd_edca_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_8/bd_edca_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_9/bd_edca_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_10/bd_edca_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_11/bd_edca_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_12/bd_edca_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_13/bd_edca_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_14/bd_edca_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_15/bd_edca_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_16/bd_edca_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_17/bd_edca_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_18/bd_edca_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_19/bd_edca_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_20/bd_edca_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_21/bd_edca_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_22/bd_edca_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_23/bd_edca_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_24/bd_edca_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_25/bd_edca_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_26/bd_edca_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_27/bd_edca_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_28/bd_edca_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_29/bd_edca_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_30/bd_edca_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_31/bd_edca_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_32/bd_edca_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_33/bd_edca_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_34/bd_edca_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_35/bd_edca_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_36/bd_edca_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_37/bd_edca_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_38/bd_edca_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_39/bd_edca_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_40/bd_edca_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_41/bd_edca_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_42/bd_edca_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_43/bd_edca_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_44/bd_edca_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_45/bd_edca_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_46/bd_edca_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_47/bd_edca_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_48/bd_edca_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_49/bd_edca_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_50/bd_edca_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_51/bd_edca_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_52/bd_edca_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_53/bd_edca_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_54/bd_edca_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_55/bd_edca_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_1/bd_edca_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_1/bd_edca_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_2/bd_edca_arinsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_3/bd_edca_rinsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_4/bd_edca_awinsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_5/bd_edca_winsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_6/bd_edca_binsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_7/bd_edca_aroutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_8/bd_edca_routsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_9/bd_edca_awoutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_10/bd_edca_woutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_11/bd_edca_boutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_12/bd_edca_arni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_12/bd_edca_arni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_13/bd_edca_rni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_13/bd_edca_rni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_14/bd_edca_awni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_14/bd_edca_awni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_15/bd_edca_wni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_15/bd_edca_wni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_16/bd_edca_bni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_16/bd_edca_bni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_20/bd_edca_s00a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_21/bd_edca_sarn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_21/bd_edca_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_22/bd_edca_srn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_22/bd_edca_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_23/bd_edca_sawn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_23/bd_edca_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_24/bd_edca_swn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_24/bd_edca_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_25/bd_edca_sbn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_25/bd_edca_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_29/bd_edca_s01a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_30/bd_edca_sarn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_30/bd_edca_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_31/bd_edca_srn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_31/bd_edca_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_32/bd_edca_sawn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_32/bd_edca_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_33/bd_edca_swn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_33/bd_edca_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_34/bd_edca_sbn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_34/bd_edca_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_35/bd_edca_m00s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_36/bd_edca_m00arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_36/bd_edca_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_37/bd_edca_m00rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_37/bd_edca_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_38/bd_edca_m00awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_38/bd_edca_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_39/bd_edca_m00wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_39/bd_edca_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_40/bd_edca_m00bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_40/bd_edca_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_42/bd_edca_m01s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_43/bd_edca_m01arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_43/bd_edca_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_44/bd_edca_m01rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_44/bd_edca_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_45/bd_edca_m01awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_45/bd_edca_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_46/bd_edca_m01wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_46/bd_edca_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_47/bd_edca_m01bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_47/bd_edca_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_49/bd_edca_m02s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_50/bd_edca_m02arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_50/bd_edca_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_51/bd_edca_m02rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_51/bd_edca_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_52/bd_edca_m02awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_52/bd_edca_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_53/bd_edca_m02wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_53/bd_edca_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_54/bd_edca_m02bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_54/bd_edca_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/workspace/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/kria_bd_smartconnect_1_0.xci
# IP: The module: 'kria_bd_smartconnect_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/bd_edca.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_0/bd_edca_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_1/bd_edca_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_2/bd_edca_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_3/bd_edca_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_4/bd_edca_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_5/bd_edca_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_6/bd_edca_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_7/bd_edca_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_8/bd_edca_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_9/bd_edca_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_10/bd_edca_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_11/bd_edca_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_12/bd_edca_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_13/bd_edca_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_14/bd_edca_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_15/bd_edca_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_16/bd_edca_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_17/bd_edca_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_18/bd_edca_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_19/bd_edca_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_20/bd_edca_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_21/bd_edca_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_22/bd_edca_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_23/bd_edca_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_24/bd_edca_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_25/bd_edca_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_26/bd_edca_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_27/bd_edca_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_28/bd_edca_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_29/bd_edca_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_30/bd_edca_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_31/bd_edca_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_32/bd_edca_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_33/bd_edca_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_34/bd_edca_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_35/bd_edca_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_36/bd_edca_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_37/bd_edca_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_38/bd_edca_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_39/bd_edca_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_40/bd_edca_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_41/bd_edca_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_42/bd_edca_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_43/bd_edca_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_44/bd_edca_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_45/bd_edca_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_46/bd_edca_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_47/bd_edca_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_48/bd_edca_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_49/bd_edca_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_50/bd_edca_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_51/bd_edca_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_52/bd_edca_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_53/bd_edca_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_54/bd_edca_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_55/bd_edca_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_1/bd_edca_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_1/bd_edca_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_2/bd_edca_arinsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_3/bd_edca_rinsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_4/bd_edca_awinsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_5/bd_edca_winsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_6/bd_edca_binsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_7/bd_edca_aroutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_8/bd_edca_routsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_9/bd_edca_awoutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_10/bd_edca_woutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_11/bd_edca_boutsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_12/bd_edca_arni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_12/bd_edca_arni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_13/bd_edca_rni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_13/bd_edca_rni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_14/bd_edca_awni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_14/bd_edca_awni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_15/bd_edca_wni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_15/bd_edca_wni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_16/bd_edca_bni_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_16/bd_edca_bni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_20/bd_edca_s00a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_21/bd_edca_sarn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_21/bd_edca_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_22/bd_edca_srn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_22/bd_edca_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_23/bd_edca_sawn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_23/bd_edca_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_24/bd_edca_swn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_24/bd_edca_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_25/bd_edca_sbn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_25/bd_edca_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_29/bd_edca_s01a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_30/bd_edca_sarn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_30/bd_edca_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_31/bd_edca_srn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_31/bd_edca_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_32/bd_edca_sawn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_32/bd_edca_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_33/bd_edca_swn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_33/bd_edca_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_34/bd_edca_sbn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_34/bd_edca_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_35/bd_edca_m00s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_36/bd_edca_m00arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_36/bd_edca_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_37/bd_edca_m00rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_37/bd_edca_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_38/bd_edca_m00awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_38/bd_edca_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_39/bd_edca_m00wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_39/bd_edca_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_40/bd_edca_m00bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_40/bd_edca_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_42/bd_edca_m01s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_43/bd_edca_m01arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_43/bd_edca_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_44/bd_edca_m01rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_44/bd_edca_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_45/bd_edca_m01awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_45/bd_edca_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_46/bd_edca_m01wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_46/bd_edca_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_47/bd_edca_m01bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_47/bd_edca_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_49/bd_edca_m02s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_50/bd_edca_m02arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_50/bd_edca_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_51/bd_edca_m02rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_51/bd_edca_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_52/bd_edca_m02awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_52/bd_edca_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_53/bd_edca_m02wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_53/bd_edca_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_54/bd_edca_m02bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/bd_0/ip/ip_54/bd_edca_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_1_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
