# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/user/workspace/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/kria_bd_smartconnect_0_0.xci
# IP: The module: 'kria_bd_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/bd_2d9b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_0/bd_2d9b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_2d9b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_2d9b_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_2d9b_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_2d9b_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_2d9b_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_2d9b_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_2d9b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_2d9b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_2d9b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_2d9b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_2d9b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_2d9b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_13/bd_2d9b_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_14/bd_2d9b_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_15/bd_2d9b_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_2d9b_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_2d9b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_2d9b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_2d9b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_20/bd_2d9b_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_21/bd_2d9b_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_2d9b_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_2d9b_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_2d9b_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_2d9b_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_2d9b_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_2d9b_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_2d9b_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_29/bd_2d9b_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_30/bd_2d9b_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_31/bd_2d9b_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_2d9b_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_2d9b_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_34/bd_2d9b_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_35/bd_2d9b_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_36/bd_2d9b_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_37/bd_2d9b_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_2d9b_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_2d9b_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_2d9b_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_41/bd_2d9b_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_42/bd_2d9b_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_43/bd_2d9b_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_44/bd_2d9b_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_45/bd_2d9b_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_46/bd_2d9b_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_47/bd_2d9b_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_48/bd_2d9b_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_49/bd_2d9b_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_50/bd_2d9b_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_51/bd_2d9b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_52/bd_2d9b_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_53/bd_2d9b_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_54/bd_2d9b_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_55/bd_2d9b_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_56/bd_2d9b_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_57/bd_2d9b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_2d9b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_2d9b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_2d9b_arsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_2d9b_rsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_2d9b_awsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_2d9b_wsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_2d9b_bsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_2d9b_s00a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_2d9b_sarn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_2d9b_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_2d9b_srn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_2d9b_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_2d9b_s01a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_2d9b_sawn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_2d9b_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_2d9b_swn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_2d9b_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_2d9b_sbn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_2d9b_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_2d9b_s02a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_2d9b_sarn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_2d9b_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_2d9b_srn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_2d9b_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_2d9b_sawn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_2d9b_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_2d9b_swn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_2d9b_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_2d9b_sbn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_2d9b_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_2d9b_s03a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_2d9b_sarn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_2d9b_sarn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_34/bd_2d9b_srn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_34/bd_2d9b_srn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_2d9b_s04a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_2d9b_sawn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_2d9b_sawn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_2d9b_swn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_2d9b_swn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_41/bd_2d9b_sbn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_41/bd_2d9b_sbn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_45/bd_2d9b_s05a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_46/bd_2d9b_sarn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_46/bd_2d9b_sarn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_47/bd_2d9b_srn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_47/bd_2d9b_srn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_48/bd_2d9b_sawn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_48/bd_2d9b_sawn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_49/bd_2d9b_swn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_49/bd_2d9b_swn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_50/bd_2d9b_sbn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_50/bd_2d9b_sbn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_51/bd_2d9b_m00s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_52/bd_2d9b_m00arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_52/bd_2d9b_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_53/bd_2d9b_m00rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_53/bd_2d9b_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_54/bd_2d9b_m00awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_54/bd_2d9b_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_55/bd_2d9b_m00wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_55/bd_2d9b_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_56/bd_2d9b_m00bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_56/bd_2d9b_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/user/workspace/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/kria_bd_smartconnect_0_0.xci
# IP: The module: 'kria_bd_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/bd_2d9b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_0/bd_2d9b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_2d9b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_2d9b_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_2d9b_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_2d9b_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_2d9b_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_2d9b_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_7/bd_2d9b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_8/bd_2d9b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_9/bd_2d9b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_2d9b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_2d9b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_2d9b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_13/bd_2d9b_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_14/bd_2d9b_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_15/bd_2d9b_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_2d9b_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_2d9b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_2d9b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_2d9b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_20/bd_2d9b_s02mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_21/bd_2d9b_s02tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_22/bd_2d9b_s02sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_2d9b_s02a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_2d9b_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_2d9b_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_2d9b_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_2d9b_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_2d9b_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_29/bd_2d9b_s03mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_30/bd_2d9b_s03tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_31/bd_2d9b_s03sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_2d9b_s03a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_2d9b_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_34/bd_2d9b_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_35/bd_2d9b_s04mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_36/bd_2d9b_s04tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_37/bd_2d9b_s04sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_2d9b_s04a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_2d9b_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_2d9b_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_41/bd_2d9b_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_42/bd_2d9b_s05mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_43/bd_2d9b_s05tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_44/bd_2d9b_s05sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_45/bd_2d9b_s05a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_46/bd_2d9b_sarn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_47/bd_2d9b_srn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_48/bd_2d9b_sawn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_49/bd_2d9b_swn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_50/bd_2d9b_sbn_3.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_51/bd_2d9b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_52/bd_2d9b_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_53/bd_2d9b_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_54/bd_2d9b_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_55/bd_2d9b_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_56/bd_2d9b_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_57/bd_2d9b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_2d9b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_1/bd_2d9b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_2/bd_2d9b_arsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_3/bd_2d9b_rsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_4/bd_2d9b_awsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_5/bd_2d9b_wsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_6/bd_2d9b_bsw_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_10/bd_2d9b_s00a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_2d9b_sarn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_11/bd_2d9b_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_2d9b_srn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_12/bd_2d9b_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_16/bd_2d9b_s01a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_2d9b_sawn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_17/bd_2d9b_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_2d9b_swn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_18/bd_2d9b_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_2d9b_sbn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_19/bd_2d9b_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_23/bd_2d9b_s02a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_2d9b_sarn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_24/bd_2d9b_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_2d9b_srn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_25/bd_2d9b_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_2d9b_sawn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_26/bd_2d9b_sawn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_2d9b_swn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_27/bd_2d9b_swn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_2d9b_sbn_1_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_28/bd_2d9b_sbn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_32/bd_2d9b_s03a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_2d9b_sarn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_33/bd_2d9b_sarn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_34/bd_2d9b_srn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_34/bd_2d9b_srn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_38/bd_2d9b_s04a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_2d9b_sawn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_39/bd_2d9b_sawn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_2d9b_swn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_40/bd_2d9b_swn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_41/bd_2d9b_sbn_2_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_41/bd_2d9b_sbn_2_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_45/bd_2d9b_s05a2s_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_46/bd_2d9b_sarn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_46/bd_2d9b_sarn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_47/bd_2d9b_srn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_47/bd_2d9b_srn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_48/bd_2d9b_sawn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_48/bd_2d9b_sawn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_49/bd_2d9b_swn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_49/bd_2d9b_swn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_50/bd_2d9b_sbn_3_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_50/bd_2d9b_sbn_3_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_51/bd_2d9b_m00s2a_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_52/bd_2d9b_m00arn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_52/bd_2d9b_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_53/bd_2d9b_m00rn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_53/bd_2d9b_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_54/bd_2d9b_m00awn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_54/bd_2d9b_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_55/bd_2d9b_m00wn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_55/bd_2d9b_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_56/bd_2d9b_m00bn_0_ooc.xdc

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_56/bd_2d9b_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/user/workspace/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
