# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/kria_bd_smartconnect_0_0.xci
# IP: The module: 'kria_bd_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/bd_2d9b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_0/bd_2d9b_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_0/bd_2d9b_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.srcs/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/kria_bd_smartconnect_0_0.xci
# IP: The module: 'kria_bd_smartconnect_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/bd_2d9b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_0/bd_2d9b_sc_ul_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/bd_0/ip/ip_0/bd_2d9b_sc_ul_0_cdc.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'kria_bd_smartconnect_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
