set_property SRC_FILE_INFO {cfile:/home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/ooc.xdc rfile:../../../../../kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_0/ooc.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/wiktork/Code/atmos_ws/vivado/kr260/kr260.runs/kria_bd_smartconnect_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property SRC_FILE_INFO {cfile:/run/media/wiktork/Data/Vitis/2026.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl rfile:../../../../../../../../../../../run/media/wiktork/Data/Vitis/2026.1/data/ip/xpm/xpm_cdc/tcl/xpm_cdc_sync_rst.tcl id:3 order:LATE scoped_inst:inst/sc_ul/inst/cdc_aresetn unmanaged:yes} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:FILTER_OUT_OF_CONTEXT} [current_design]
create_clock -period 5.000 -name aclk [get_ports aclk]
set_property src_info {type:XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells inst]
current_instance inst/sc_ul/inst/cdc_aresetn
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:NONE read:READ} [current_design]
set_false_path -to [get_cells {syncstages_ff_reg[0]}]
