# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-26562-cachyos-x8664/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter writeSynthRtdsInDcp false
    rt::set_parameter datapathDensePacking false
    set rt::partid xck26-sfvc784-2LV-c
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/f0b6/hdl/verilog
    /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/00fe/hdl/verilog
    /run/media/wiktork/Data/Vitis/2026.1/data/rsb/busdef
  } {
      /run/media/wiktork/Data/Vitis/2026.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /run/media/wiktork/Data/Vitis/2026.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /run/media/wiktork/Data/Vitis/2026.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/0848/hdl/sc_switchboard_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_2/synth/bd_ed5a_arsw_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_3/synth/bd_ed5a_rsw_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_4/synth/bd_ed5a_awsw_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_5/synth/bd_ed5a_wsw_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_6/synth/bd_ed5a_bsw_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/3d9a/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_7/synth/bd_ed5a_s00mmu_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/7785/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_8/synth/bd_ed5a_s00tr_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/3051/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_9/synth/bd_ed5a_s00sic_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/852f/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_10/synth/bd_ed5a_s00a2s_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/00fe/hdl/sc_node_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_11/synth/bd_ed5a_sarn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_12/synth/bd_ed5a_srn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_13/synth/bd_ed5a_s01mmu_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_14/synth/bd_ed5a_s01tr_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_15/synth/bd_ed5a_s01sic_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_16/synth/bd_ed5a_s01a2s_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_17/synth/bd_ed5a_sawn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_18/synth/bd_ed5a_swn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_19/synth/bd_ed5a_sbn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_20/synth/bd_ed5a_s02mmu_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_21/synth/bd_ed5a_s02tr_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_22/synth/bd_ed5a_s02sic_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_23/synth/bd_ed5a_s02a2s_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_24/synth/bd_ed5a_sarn_1.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_25/synth/bd_ed5a_srn_1.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_26/synth/bd_ed5a_sawn_1.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_27/synth/bd_ed5a_swn_1.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_28/synth/bd_ed5a_sbn_1.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/fca9/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_29/synth/bd_ed5a_m00s2a_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_30/synth/bd_ed5a_m00arn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_31/synth/bd_ed5a_m00rn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_32/synth/bd_ed5a_m00awn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_33/synth/bd_ed5a_m00wn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_34/synth/bd_ed5a_m00bn_0.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/c7d2/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_35/synth/bd_ed5a_m00e_0.sv
    }
      rt::read_verilog -include {
    /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/f0b6/hdl/verilog
    /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/00fe/hdl/verilog
    /run/media/wiktork/Data/Vitis/2026.1/data/rsb/busdef
  } {
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/synth/bd_ed5a.v
      /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/synth/kria_bd_smartconnect_0_1.v
    }
      rt::read_vhdl -lib xpm /run/media/wiktork/Data/Vitis/2026.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_17 /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ipshared/9438/hdl/proc_sys_reset_v5_0_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib /home/wiktork/Code/atmos_ws/vivado/kr260/kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_smartconnect_0_1/bd_0/ip/ip_1/synth/bd_ed5a_psr_aclk_0.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-26562-cachyos-x8664/realtime/kria_bd_smartconnect_0_1_synth.xdc
    rt::sdcChecksum
    set rt::top kria_bd_smartconnect_0_1
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::ioInsertion false
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: out_of_context
    rt::set_parameter writeSynthRtdsInDcp false
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-26562-cachyos-x8664/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
